# Generated by Django 4.1.2 on 2023-08-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyaclub_app', '0002_alter_deposit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('Approved', 'Approved'), ('rejeted', 'rejected')], default='pending', max_length=200),
        ),
    ]
