# Generated by Django 4.1.2 on 2023-08-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyaclub_app', '0004_alter_deposit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='Transaction_id',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='purpose',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=50),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='expense',
            name='purpose',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='fine',
            name='status',
            field=models.CharField(choices=[('paid', 'paid'), ('unpaid', 'unpaid')], default='unpaid', max_length=30),
        ),
    ]
