# Generated by Django 4.1.2 on 2023-09-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyaclub_app', '0005_deposit_transaction_id_alter_asset_asset_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=300)),
                ('amount', models.PositiveIntegerField()),
                ('date_of_income', models.DateTimeField()),
                ('receipt', models.ImageField(blank=True, upload_to='income/%Y/%m/%d')),
            ],
        ),
        migrations.AlterField(
            model_name='deposit',
            name='Transaction_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='telephone',
            field=models.PositiveIntegerField(),
        ),
    ]
